#!/usr/bin/with-contenv bash

[[ -n ${DEBUG} ]] && set -x
[[ -n ${COUNTRY} && -z ${CONNECT} ]] && CONNECT=${COUNTRY}
[[ "${PGID:-""}" =~ ^[0-9]+$ ]] && groupmod -g $PGID -o vpn

DOCKER_NET="$(ip -o addr show dev eth0 | awk '$3 == "inet" {print $4}')" 

create_tun_device() {
	mkdir -p /dev/net
	[[ -c /dev/net/tun ]] || mknod -m 0666 /dev/net/tun c 10 200
}

setup_nordvpn() {
	[[ -n ${TECHNOLOGY} ]] && nordvpn set technology ${TECHNOLOGY}
	[[ -n ${PROTOCOL} ]]  && nordvpn set protocol ${PROTOCOL} 
	[[ -n ${OBFUSCATE} ]] && nordvpn set obfuscate ${OBFUSCATE}
	[[ -n ${CYBER_SEC} ]] && nordvpn set cybersec ${CYBER_SEC}
	[[ -n ${KILL_SWITCH} ]] && nordvpn set killswitch ${KILL_SWITCH}
	[[ -n ${DNS} ]] && nordvpn set dns ${DNS//[;,]/ }
	[[ -n ${DOCKER_NET} ]]  && nordvpn whitelist add subnet ${DOCKER_NET}
	[[ -n ${NETWORK} ]]  && for net in ${NETWORK//[;,]/ };  do nordvpn whitelist add subnet ${net};  done
	[[ -n ${PORTS} ]]  && for port in ${PORTS//[;,]/ };  do nordvpn whitelist add port ${port};  done
	[[ -n ${DEBUG} ]] && nordvpn -version && nordvpn settings
}

pkill nordvpnd 
rm -f /run/nordvpnd.sock
sg vpn -c nordvpnd & 

while [ ! -S /run/nordvpnd.sock ]; do
	sleep 0.25
done

nordvpn login -u ${USER} -p "${PASS}"

setup_nordvpn
create_tun_device

nordvpn connect ${CONNECT} || exit 1
nordvpn status

tail -f --pid=$(pidof nordvpnd) /var/log/nordvpn/daemon.log
